### ISSUE TITLE
Suggestion: Clicking emoji appends to chat

### ISSUE THREAD

**Issue by SandroVA** [hjdarnel/runelite-emoji-palette-plugin#1]
I'm not sure if this is possible but it would be really awesome if clicking an emoji can append said emoji to the message I am writing in chat.

**Comment by hjdarnel** [comment]
Thanks for the suggestion! I agree that it would be great, but as far as I know the client isn't allowed to input into the chat box. I had this discussion with RuneLite devs when I first wrote the plugin. I also considered putting the code into the clipboard, but you can't paste into the chat box right now either.
